[graph]
all-features = true
targets = [
  { triple = "x86_64-pc-windows-msvc" },
  { triple = "x86_64-unknown-linux-gnu" },
  { triple = "x86_64-unknown-linux-musl" },
]

[advisories]
ignore = [
    # allow `paste`, which is no longer maintained
    "RUSTSEC-2024-0436"
]
version = 2
yanked = "deny"

[bans]
multiple-versions = "allow"

[licenses]
allow = ["Apache-2.0", "BSD-3-Clause", "BSL-1.0", "MIT", "Unicode-3.0", "Zlib", "ISC", "OpenSSL"]
version = 2

[licenses.private]
ignore = true
